#Kabanero! on activate substitute Digest for text '@Digest@'
#
# This task will deploy the application image to the cluster using the info in the app-deploy.yaml file.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task-@Digest@
spec:
  resources:
    inputs:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  params:
  - name: app-deploy-file-name
    default: app-deploy.yaml
  - name: docker-imagename
    type: string
    default: ""
  - name: docker-imagetag
    type: string
    default: ""
  steps:
  - name: enforce-stack-policy-pre-deploy
    securityContext:
      privileged: true
    image: kabanero/kabanero-utils@sha256:f9ceeb7d2ba94c2216d430e7fb0b16eb6e36da41de79222f47aaac82dfd024da
    command: ["/bin/bash"]
    args:
      - -c
      - |
        INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE=$( /scripts/imageurl_imagename_lowercase.sh -u $(inputs.resources.docker-image.url) -n $(inputs.params.docker-imagename) -t $(inputs.params.docker-imagetag) )
        retVal=$?
        if [ $retVal -ne 0 ]; then
             echo "The script failed(/scripts/imageurl_imagename_lowercase.sh) Reason: $INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE" >&2
             exit $retVal
        fi
        echo "INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE=$INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE"
        /scripts/enforce_deploy_stack_policy.sh $INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE
    env:  
    - name: gitsource
      value: git-source
  - name: deploy-image
    image: kabanero/kabanero-utils@sha256:8020573657ed1b80e2b872a37719d6398ee78219296fe6180733f54425f7bd6a
    command: ['/bin/sh']
    args:
      - -c
      - |
         kubectl apply -f  /workspace/$gitsource/${YAMLFILE}
    env:
    - name: gitsource
      value: git-source
    - name: YAMLFILE
      value: $(inputs.params.app-deploy-file-name)