apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: image-scan-condition
spec:
  params:
  - name: "event-type"
    type: string
    description: "The Git event type"
  - name: "event-ref"
    type: string
    description: "The Git event ref"
  check:
    name: image-scan-condition
    image: kabanero/kabanero-utils@sha256:12bd19bbdca1fcbab070c494e79d29f9668f3e0c58b2d2f2388b748d4eeca41c
    command: ["/bin/sh"]
    args:
      - -ce
      - |
        echo "Checking if image-scan-task should execute..."
        echo "Event-type = $(params.event-type)"
        echo "Event-ref = $(params.event-ref)"
        if [[ $(params.event-type) == "push" && $(params.event-ref) == "refs/heads/master" ]]; then
          echo "Event type is a push to master"
          exit 0
        else
          echo "Event type is not a push to master. Skipping image-scan-task execution"
          exit 1
        fi